translate quickguide_create_a_mod.md
TaleWorlds/Documentations pull request #11
Opened 2020-10-09 19:32 UTC by WuZhuoran

2020-10-09 23:15 UTC, Bisstocuz commented on docs/content/schinese/Asset Management/quickguide_create_a_mod.md
> +* Atmospheres: 此文件夹包含可在游戏中使用的不同大气层模板。可以从编辑器将新的大气层保存到任何 Mod。
这里 Atmosphere 肯定不是翻译成大气层，建议“周围环境”或“氛围”或其他更合适的词语。

2020-10-09 23:16 UTC, Bisstocuz commented on docs/content/schinese/Asset Management/quickguide_create_a_mod.md
> +* ModuleData: 此文件夹有许多包含了重要游戏逻辑的 xml 文件。"project.mbproj" 文件管理着将被加载到该文件夹内的 xml 文件。这些 xml 涵盖了从动画和套装到派系、部队、物品等内容。
Faction 官方译名为“阵营”，请将“派系”替换为“阵营”

2020-10-09 23:16 UTC, Bisstocuz requested changes
请留意评论

2020-10-09 23:32 UTC, WuZhuoran commented on docs/content/schinese/Asset Management/quickguide_create_a_mod.md
> +* Atmospheres: 此文件夹包含可在游戏中使用的不同大气层模板。可以从编辑器将新的大气层保存到任何 Mod。
这个是我疏忽了 忘记改了 马上修改 根据目前的资料，这里可以理解为氛围，但是考虑到这个在游戏Mod中也是可以修改的
所以我打算翻译成 周围环境

2020-10-09 23:33 UTC, WuZhuoran commented on docs/content/schinese/Asset Management/quickguide_create_a_mod.md
> +* ModuleData: 此文件夹有许多包含了重要游戏逻辑的 xml 文件。"project.mbproj" 文件管理着将被加载到该文件夹内的 xml 文件。这些 xml 涵盖了从动画和套装到派系、部队、物品等内容。
收到

2020-10-09 23:51 UTC, Bisstocuz approved these changes

2020-10-10 01:53 UTC, Bisstocuz approved these changes

2020-10-13 08:16 UTC, merged