[Translate] Adding Custom Sounds.md to Chinese
TaleWorlds/Documentations pull request #23
Opened 2020-10-10 18:16 UTC by WuZhuoran

Also fix some typo.

2020-10-10 18:32 UTC, Bisstocuz requested changes
整个文本很多句子都有语序很奇怪的毛病，需要润色

2020-10-10 18:32 UTC, Bisstocuz commented on docs/content/schinese/Playing Sounds/Adding Custom Sounds.md
> +《霸主》的音频系统是基于 FMOD 音频引擎专利 建立的。
“《霸主》的音频系统是基于 FMOD 音频引擎建立的。”就足够了，专利反而冗余，不要为了求得每个词都有对应翻译而让译文主体出现偏差。

2020-10-10 18:47 UTC, WuZhuoran commented on docs/content/schinese/Playing Sounds/Adding Custom Sounds.md
> +《霸主》的音频系统是基于 FMOD 音频引擎专利 建立的。
fixed.

2020-10-10 18:48 UTC, WuZhuoran commented
> 整个文本很多句子都有语序很奇怪的毛病，需要润色

哪些方面需要修改？是现在修改还是之后？

2020-10-11 01:45 UTC, Bisstocuz requested changes
先处理这些吧，精修以后再来。
以下所有 comments 仅供参考，不一定要全部执行，请译者斟酌。

2020-10-11 01:45 UTC, Bisstocuz commented on docs/content/schinese/Playing Sounds/Adding Custom Sounds.md
> +为了让音频引擎性能好同时大家也都可以用到，我们需要建立一个 中间层  (InterLayer)。
“为了让音频引擎性能好同时大家也都可以用到”→“为了保持音频引擎性能的同时让大家都能使用它”（语序调整）

2020-10-11 01:45 UTC, Bisstocuz commented on docs/content/schinese/Playing Sounds/Adding Custom Sounds.md
> +## 基本指南
此处“Basic”下的内容含义是更倾向于“基础”还是“基本”？译为“基础工作指南”是否更合适？

2020-10-11 01:45 UTC, Bisstocuz commented on docs/content/schinese/Playing Sounds/Adding Custom Sounds.md
> +    - mission_siege_loud (大型围城的声响，比如巨石冀中墙壁、火焰投石车以及城门破坏的音频)
错别字“冀中”→“击中”

2020-10-11 01:45 UTC, Bisstocuz commented on docs/content/schinese/Playing Sounds/Adding Custom Sounds.md
> +* **'path'**: 声音文件的路径。路径是相对于你 Mod 的 ModuleSounds 文件夹，你可以创建自己的子目录。
“路径是相对于你 Mod 的 ModuleSounds 文件夹”→“路径是基于你 Mod 的 ModuleSounds 文件夹的相对路径”（描述语序调整）

2020-10-11 01:47 UTC, Bisstocuz commented on docs/content/english/Playing Sounds/Adding Custom Sounds.md
>  To keep audio engine performant while making it accessible to anyone, we needed to create an interlayer.
不说还没注意，这行的 performance 打错了还。

2020-10-12 05:20 UTC, Bisstocuz approved these changes

2020-10-13 11:54 UTC, OzgurEraslan commented on docs/content/english/Playing Sounds/Adding Custom Sounds.md
>  To keep audio engine performant while making it accessible to anyone, we needed to create an interlayer.
![image](https://user-images.githubusercontent.com/2129621/95857214-f21f6800-0d63-11eb-87c4-15079ff6f8a2.png)

I believe performant is the correct usage.

2020-10-13 11:59 UTC, merged