docs: translate distance_tool
TaleWorlds/Documentations pull request #38
Opened 2020-10-17 04:10 UTC by WuZhuoran

translate http://docs.modding.bannerlord.com/zh_cn/editor/scene-editor/distance_tool/

2020-10-17 04:51 UTC, Yuxuan1993 commented on docs/content/schinese/Editor/Scene Editor/distance_tool.md
> +* <b> 蓝线 </b> 展示了经纬度坐标距离。
这里可否考虑替换成“横向和纵向”？这样表述或许会更通俗

2020-10-17 04:51 UTC, Yuxuan1993 commented on docs/content/schinese/Editor/Scene Editor/distance_tool.md
> +这工具可以通过按 <b> Alt + D </b> 或者点击编辑器工具栏上对应按钮来取消该模式。为了以后方便，测量的图标 (Gizmo) 在取消模式后也会一直可见。按住 <b> Alt + Shift + D </b> 来清除屏幕中的测量图标。
“工具可通过按键取消模式”的句式可能有些不通顺，这里的意思是否表达的是”该模式/工具可通过按Alt + D或者点击编辑器工具栏上对应按钮来取消（操作）“？

2020-10-17 04:54 UTC, Bisstocuz requested changes

2020-10-17 04:54 UTC, Bisstocuz commented on docs/content/schinese/Editor/Scene Editor/distance_tool.md
> +* <b> 黄圆 </b> 描述了范围。
“黄圆”是？还是说想表达的是“黄色圆圈”？

2020-10-17 04:54 UTC, Bisstocuz commented on docs/content/schinese/Editor/Scene Editor/distance_tool.md
> +使用时，按住 <b> 鼠标左键 </b>，在场景内从一个点拖动鼠标到另一个点来测量距离。如果靠近一个点过近，工具会默认吸附在顶点上，按住 <b>Left Shift</b> 来取消吸附。
“Left Shift” 中的 Left 需要翻译，应该译为“左 Shift”。

2020-10-17 06:08 UTC, WuZhuoran commented on docs/content/schinese/Editor/Scene Editor/distance_tool.md
> +* <b> 蓝线 </b> 展示了经纬度坐标距离。
原文里面是经纬度的含义吧 因为经纬度距离是一个比较常见的 数据

2020-10-17 06:09 UTC, WuZhuoran commented on docs/content/schinese/Editor/Scene Editor/distance_tool.md
> +这工具可以通过按 <b> Alt + D </b> 或者点击编辑器工具栏上对应按钮来取消该模式。为了以后方便，测量的图标 (Gizmo) 在取消模式后也会一直可见。按住 <b> Alt + Shift + D </b> 来清除屏幕中的测量图标。
fixed

2020-10-17 06:09 UTC, WuZhuoran commented on docs/content/schinese/Editor/Scene Editor/distance_tool.md
> +使用时，按住 <b> 鼠标左键 </b>，在场景内从一个点拖动鼠标到另一个点来测量距离。如果靠近一个点过近，工具会默认吸附在顶点上，按住 <b>Left Shift</b> 来取消吸附。
fixed.

2020-10-17 06:10 UTC, WuZhuoran commented on docs/content/schinese/Editor/Scene Editor/distance_tool.md
> +* <b> 黄圆 </b> 描述了范围。
fixed

2020-10-17 07:10 UTC, Bisstocuz approved these changes

2020-10-19 15:38 UTC, Bisstocuz approved these changes

2020-10-20 05:23 UTC, Bisstocuz commented
Able to be merged.

2020-10-20 11:50 UTC, merged