Translate Path Editing md
TaleWorlds/Documentations pull request #40
Opened 2020-10-19 02:08 UTC by WuZhuoran

http://docs.modding.bannerlord.com/zh_cn/editor/scene-editor/path_editing/

2020-10-19 02:37 UTC, Bisstocuz approved these changes

2020-10-19 02:38 UTC, Bisstocuz requested changes

2020-10-19 02:38 UTC, Bisstocuz commented on docs/content/schinese/Editor/Scene Editor/path_editing.md
> +阶段设计器 (Level designer) 可以在场景编辑器 (Scene Editor) 中轻易的增加、修改和删除路径 (Path) 和路径点 (Path Point)。
这个 Level Designer 有待商榷，现有成译一般为“关卡设计师”

2020-10-19 03:18 UTC, WuZhuoran commented on docs/content/schinese/Editor/Scene Editor/path_editing.md
> +阶段设计器 (Level designer) 可以在场景编辑器 (Scene Editor) 中轻易的增加、修改和删除路径 (Path) 和路径点 (Path Point)。
对 这个我也是我想和大家商榷一下的。

2020-10-19 03:33 UTC, Bisstocuz approved these changes

2020-10-19 15:38 UTC, Bisstocuz approved these changes

2020-10-20 05:20 UTC, Bisstocuz approved these changes
Able to be merged.

2020-10-20 11:49 UTC, merged