[Translate] Adding prefabs.md to Chinese
TaleWorlds/Documentations pull request #42
Opened 2020-10-19 04:57 UTC by Yuxuan1993

2020-10-19 05:00 UTC, Bisstocuz approved these changes

2020-10-19 05:04 UTC, Bisstocuz commented
The file "meshes.md" has been pulled again in this pull request, so #37 will be closed.

2020-10-19 05:37 UTC, WuZhuoran commented on docs/content/schinese/Asset Management/Asset Types/prefabs.md
> +在RGL中，实体是包含所有网格，粒子，脚本组件，遮挡物和物理对象的容器。它们可以容纳其他实体来作为其子实体。这些子实体有自己的变体存在，决定了它们在整个世界中的位置，比例和旋转角度。
RGL 是否需要解释一下？

2020-10-19 05:39 UTC, WuZhuoran commented on docs/content/schinese/Asset Management/Asset Types/prefabs.md
> +在RGL中，实体是包含所有网格，粒子，脚本组件，遮挡物和物理对象的容器。它们可以容纳其他实体来作为其子实体。这些子实体有自己的变体存在，决定了它们在整个世界中的位置，比例和旋转角度。
同时建议 `网格，粒子，脚本组件，遮挡物和物理对象` 这些部分 每一个后面加上 英文原文 
`网格 (meshed)` 这样

2020-10-19 05:40 UTC, WuZhuoran commented on docs/content/schinese/Asset Management/Asset Types/prefabs.md
> +预制件：预制件属于模板实体，即便是复杂的实体可以直接一次构造，并在之后保存为预制物件，以便在任何场景中随时使用。后期对预制件的更新也会对已经完成的场景造成影响。在《霸主》中，几乎所有的任务对象和场景道具都是预制件。
`预制件 (Prefabs)` 最好

2020-10-19 05:43 UTC, Yuxuan1993 commented on docs/content/schinese/Asset Management/Asset Types/prefabs.md
> +在RGL中，实体是包含所有网格，粒子，脚本组件，遮挡物和物理对象的容器。它们可以容纳其他实体来作为其子实体。这些子实体有自己的变体存在，决定了它们在整个世界中的位置，比例和旋转角度。
好的，不过RGL在原文里面表达的是什么？是否应该是《霸主》编辑器的意思?

2020-10-19 05:52 UTC, WuZhuoran commented on docs/content/schinese/Asset Management/Asset Types/prefabs.md
> +在RGL中，实体是包含所有网格，粒子，脚本组件，遮挡物和物理对象的容器。它们可以容纳其他实体来作为其子实体。这些子实体有自己的变体存在，决定了它们在整个世界中的位置，比例和旋转角度。
RGL 是一种 图形库吧

2020-10-21 04:56 UTC, Bisstocuz approved these changes
Able to be merged.

2020-10-21 06:28 UTC, WuZhuoran approved these changes

2020-10-21 15:02 UTC, Bisstocuz requested changes
根据 #44 ，RGL 是一个TaleWorlds自定义的缩写，请纠正。

2020-10-22 05:12 UTC, Bisstocuz approved these changes
Able to be merged.

2020-10-22 08:00 UTC, merged