Translate destructible component
TaleWorlds/Documentations pull request #52
Opened 2020-11-12 06:50 UTC by Oshibuki

#2

2020-11-13 12:51 UTC, Bisstocuz requested changes

2020-11-13 12:51 UTC, Bisstocuz commented on docs/content/schinese/Authoring Mission Scenes/Script Components/bannerlord_destructible_component.md
> +一个实体可以有多个DestructibleComponent脚本。例如，撞锤是可破坏的，但它的顶棚也可以被单独摧毁。对子级施加的任何损坏也将应用于它的父级(可能是多层父级)。
请使用中文括号

2020-11-13 12:51 UTC, Bisstocuz commented on docs/content/schinese/Authoring Mission Scenes/Script Components/bannerlord_destructible_component.md
> +### 示例1：带有易碎城垛（merlon）的城墙
breakable → 可破坏的

2020-11-14 01:54 UTC, Oshibuki commented
@Bisstocuz  已修改

2020-11-14 03:54 UTC, Bisstocuz approved these changes
Able to be merged.

2020-11-16 02:08 UTC, Oshibuki commented
@OzgurEraslan  Please merge this pr.

2020-11-23 12:24 UTC, merged