Translate scene barrier builder
TaleWorlds/Documentations pull request #53
Opened 2020-11-12 07:30 UTC by Oshibuki

#2

2020-11-13 12:53 UTC, Bisstocuz requested changes

2020-11-13 12:53 UTC, Bisstocuz commented on docs/content/schinese/Authoring Mission Scenes/Script Components/scene_barrier_builder.md
> +- 您可以使用"Go to Entity"按钮转到该实体，并更改其选项，例如高度，该实体名为"path_barrier_PATHNAME"
这个 PATHNAME 应该是（解释用途）变量名，可译

2020-11-13 12:53 UTC, Bisstocuz commented on docs/content/schinese/Authoring Mission Scenes/Script Components/scene_barrier_builder.md
> +- 随心所欲的创建路径
语法错误，“的”替换成“地”

2020-11-14 02:18 UTC, Oshibuki commented
@Bisstocuz resolved

2020-11-14 03:55 UTC, Bisstocuz approved these changes
Able to be merged.

2020-11-23 12:24 UTC, merged