Translate skeleton editor
TaleWorlds/Documentations pull request #56
Opened 2020-11-13 02:05 UTC by Oshibuki

#2

2020-11-13 12:59 UTC, Bisstocuz requested changes

2020-11-13 12:59 UTC, Bisstocuz commented on docs/content/schinese/Editor/Resource Editors/skeleton_editor.md
> +**Free**>：表示该关节可以在该轴上自由移动。
这里多了一个“>”字符，可能影响到网页代码转换。

2020-11-14 02:37 UTC, Oshibuki commented
@Bisstocuz  resolved

2020-11-14 03:55 UTC, Bisstocuz approved these changes
Able to be merged.

2020-11-23 12:25 UTC, merged