Translate entity inspector
TaleWorlds/Documentations pull request #59
Opened 2020-11-13 10:17 UTC by Oshibuki

#2

2020-11-13 13:28 UTC, Bisstocuz requested changes

2020-11-13 13:28 UTC, Bisstocuz commented on docs/content/schinese/Editor/Scene Editor/entity_inspector.md
>  #### Scale ####
这里没有翻译

2020-11-14 02:40 UTC, Oshibuki commented
@Bisstocuz resolved

2020-11-14 03:56 UTC, Bisstocuz approved these changes
Able to be merged.

2020-11-23 12:25 UTC, merged