Translate scene level system
TaleWorlds/Documentations pull request #61
Opened 2020-11-14 04:52 UTC by Oshibuki

#2

2020-11-15 13:39 UTC, Bisstocuz requested changes

2020-11-15 13:39 UTC, Bisstocuz commented on docs/content/schinese/Editor/Scene Editor/level_system.md
> +title = "场景等级系统"
Level 是关卡（场景）的意思，同样，Level Designer 即关卡设计师，下同

2020-11-16 02:08 UTC, Bisstocuz approved these changes
Able to be merged.

2020-11-22 04:36 UTC, WuZhuoran approved these changes

2020-11-23 12:26 UTC, merged