[Translate] Adding asset_name_convetions.md to Chinese
TaleWorlds/Documentations pull request #64
Opened 2020-11-28 14:37 UTC by Yuxuan1993

2020-11-30 02:12 UTC, Bisstocuz requested changes

2020-11-30 02:12 UTC, Bisstocuz commented on docs/content/schinese/Asset Management/Asset Types/asset_naming_conventions.md
> +该范例中，我们从 asset.fbx 文件中导入两个网格：wall_damaged, wall_damaged_v2。其中wall_damaged_v2有一个lod文件，而wall_damaged有两个lod文件。如果你的建模软件不支持用"."命名(如Maya)，你也可以用"_"代替". "来指定网格(如wall_damaged_v2_lod1)。
转义字符"\\_"反斜杠缺失

2020-11-30 05:34 UTC, Yuxuan1993 commented on docs/content/schinese/Asset Management/Asset Types/asset_naming_conventions.md
> +该范例中，我们从 asset.fbx 文件中导入两个网格：wall_damaged, wall_damaged_v2。其中wall_damaged_v2有一个lod文件，而wall_damaged有两个lod文件。如果你的建模软件不支持用"."命名(如Maya)，你也可以用"_"代替". "来指定网格(如wall_damaged_v2_lod1)。
已修正

2020-12-02 08:57 UTC, Bisstocuz requested changes

2020-12-02 08:57 UTC, Bisstocuz commented on docs/content/schinese/Asset Management/Asset Types/asset_naming_conventions.md
> +该范例中，我们从 asset.fbx 文件中导入两个网格：wall_damaged, wall_damaged_v2。其中wall_damaged_v2有一个lod文件，而wall_damaged有两个lod文件。如果你的建模软件不支持用转义字符"\_"命名(如Maya)，您也可以用"_"代替". "来指定网格(如wall_damaged_v2_lod1)。
你在改什么？我怎么看不懂了？为什么要把“.”改成“\\_”，我说的是给“_”加上原文应该有的反斜杠。

2020-12-02 12:04 UTC, Yuxuan1993 commented on docs/content/schinese/Asset Management/Asset Types/asset_naming_conventions.md
> +该范例中，我们从 asset.fbx 文件中导入两个网格：wall_damaged, wall_damaged_v2。其中wall_damaged_v2有一个lod文件，而wall_damaged有两个lod文件。如果你的建模软件不支持用转义字符"\_"命名(如Maya)，您也可以用"_"代替". "来指定网格(如wall_damaged_v2_lod1)。
那啥……我没太明白，可以具体解释一下吗？

2020-12-02 12:05 UTC, Yuxuan1993 commented on docs/content/schinese/Asset Management/Asset Types/asset_naming_conventions.md
> +该范例中，我们从 asset.fbx 文件中导入两个网格：wall_damaged, wall_damaged_v2。其中wall_damaged_v2有一个lod文件，而wall_damaged有两个lod文件。如果你的建模软件不支持用转义字符"\_"命名(如Maya)，您也可以用"_"代替". "来指定网格(如wall_damaged_v2_lod1)。
改错符号了，非常抱歉，应该是后面一个

2020-12-02 15:30 UTC, Bisstocuz approved these changes
Able to be merged.

2020-12-03 10:48 UTC, merged