Translate asset types animations
TaleWorlds/Documentations pull request #75
Opened 2021-02-28 14:19 UTC by Oshibuki

first edition

2021-02-28 14:37 UTC, Bisstocuz commented on docs/content/schinese/Asset Management/Asset Types/animations.md
> +#### 为Bannerlord 导出动画
Bannerlord 左边缺失空格，格式不对称

2021-02-28 14:40 UTC, Bisstocuz requested changes

2021-02-28 14:40 UTC, Bisstocuz commented on docs/content/schinese/Asset Management/Asset Types/animations.md
> +#### 为Bannerlord 导出动画
Bannerlord 左边缺失空格，格式不对称

2021-03-01 03:43 UTC, Bisstocuz approved these changes

2021-04-06 05:41 UTC, WuZhuoran approved these changes

2021-04-11 13:33 UTC, merged